version: '3'

services:
  server:
    build: .
    restart: always
    container_name: server_container
    env_file:
      - .env
    ports:
      - 3000:8080
    depends_on:
      - mysql_db
    networks:
      - server_network

  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - server_network

networks:
  server_network:
    name: server_network
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/16
